### ISSUE TITLE
Error with command sf after install plugin-lightning-dev 

### ISSUE THREAD

**Issue by UkonGOTO** [salesforcecli/plugin-lightning-dev#176]
### Summary

In VSCode 

After install @salesforce/plugin-lightning-dev 
sf command return
AuthDecryptError: Failed to decipher auth data. reason: Unsupported state or unable to authenticate data.
    Code: AuthDecryptError

### Steps To Reproduce:

> sf plugins install @salesforce/plugin-lightning-dev

after install

> sf doctor

   AuthDecryptError: Failed to decipher auth data. reason: Unsupported state or unable to authenticate data.
    Code: AuthDecryptError

after uninstall  @salesforce/plugin-lightning-dev

> sf doctor
All is OK

**VS Code Version**:

1.93.1

**SFDX CLI Version**:

@salesforce/cli/2.58.7 win32-x64 node-v20.17.0

**OS and version**:

Windows 11

**Comment by UkonGOTO** [comment]
After installing plugin-lightning-dev when starting VSCode the following error appears : 

Salesforce Extensions for VS Code encountered a problem while configuring your environment. Some features might not work. For details, click Help > Toggle Developer Tools or check the Salesforce CLI logs in ~/.sfdx/sfdx.log.

**Comment by UkonGOTO** [comment]
Sorry, I closed the issue by mistake

**Comment by UkonGOTO** [comment]
Command :
> sf lightning dev app

Return :
Error (AuthDecryptError): Failed to decipher auth data. reason: Unsupported state or unable to authenticate data.

sf log :
"name":"sf:oclif","msg":"AuthDecryptError: Failed to decipher auth data. reason: Unsupported state or unable to authenticate data.\n    at SfCommandError.from (file:///C:/Users/xxx/AppData/Local/sf/node_modules/@salesforce/plugin-lightning-dev/node_modules/@salesforce/sf-plugins-core/lib/SfCommandError.js:39:16)\n    at LightningDevApp.catch (file:///C:/Users/xxx/AppData/Local/sf/node_modules/@salesforce/plugin-lightning-dev/node_modules/@salesforce/sf-plugins-core/lib/sfCommand.js:315:47)\n    at LightningDevApp._run (C:/Users/xxx/AppData/Local/sf/node_modules/@salesforce/plugin-lightning-dev/node_modules/@oclif/core/lib/command.js:305:29)\n    at async Config.runCommand (C:/Users/xxx/AppData/Local/sf/client/2.58.7-ed27925/node_modules/@oclif/core/lib/config/config.js:424:25)\n    at async run (C:/Users/xxx/AppData/Local/sf/client/2.58.7-ed27925/node_modules/@oclif/core/lib/main.js:95:16)\n
